### PR TITLE
Let it build with GHC 9.6

### PR DESCRIPTION
**Pull request by rvl**
GHC 9.6 includes [mtl-2.3.1](https://hackage.haskell.org/package/mtl-2.3.1) (see [release notes](https://downloads.haskell.org/ghc/9.6.1/docs/users_guide/9.6.1-notes.html#included-libraries)). This version no longer exports `Control.Monad.Error`, causing the build of ConfigFile to fail.

This PR makes the necessary adjustments for mtl>=2.3.

It also adds some GitHub CI to run the tests under cabal.

Two tests were failing so I include fixes for those.

Thanks

### CODE REVIEW

**Comment by bcb** [comment]
Works great. Thank you @rvl

**Comment by jgoerzen** [comment]
Hi folks, I'm going to merge this but please note I announced I was no longer maintaining this package and offered it up for adoption a number of years ago.  So I would happily hand it off to someone else.

**Comment by drlkf** [comment]
@jgoerzen could you maybe change the README and the `About` wiki link to reflect this position? Those links are dead so it's not obvious to the reader that you are looking for a new maintainer

**Comment by jgoerzen** [comment]
Updated README

**Pull request merged**
